<?php
namespace App\Domain\Farm\Providers;

use App\Domain\Farm\Events\HarvestCreated;
use App\Domain\Farm\Services\Farm;
use App\Domain\Farm\Listeners\Harvest;
use App\Domain\Farm\Listeners\InitFarm;
use Illuminate\Foundation\Support\Providers\EventServiceProvider;
use Illuminate\Console\Events\CommandStarting;
use Illuminate\Support\Facades\Event;

class FarmServiceProvider extends EventServiceProvider
{
    public function register()
    {
        $this->app->singleton(Farm::class, Farm::class);
        parent::register(); // TODO: Change the autogenerated stub
    }

    public function boot(): void
    {
        // init farm animals
        Event::listen(
            CommandStarting::class,
            InitFarm::class,
        );

        // harvesting one harvest event
        Event::listen(
            HarvestCreated::class,
            Harvest::class,
        );
    }
}
